# Generated by Django 2.1.3 on 2018-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptureVideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='Progress')),
            ],
        ),
    ]
