# Generated by Django 2.1.4 on 2018-12-16 16:35

import CaptureVideo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptureVideo', '0003_auto_20181202_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='stage',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=CaptureVideo.models.get_image_path),
        ),
    ]
